name: Sync can-utils

on:
  schedule:
    - cron: '17 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: tubbywrestler/aur-bin-chicken/.github/workflows/sync-and-build.yml@master
    with:
      aur_pkgbase: can-utils
    permissions:
      contents: write
